services:
    hammerdb:
        network_mode: host
        platform: linux/amd64
        build: 
          context: .
          dockerfile: dockerfile
          platforms:
            - linux/amd64
        env_file:
          - hammerdb.env
        environment:
          - RUN_MODE
          - BENCHMARK
        volumes:
          - ./scripts:/opt/HammerDB-4.7/scripts
          - ./output:/tmp
        command: ["/entrypoint.sh"]