services:
    hammerdb:
        network_mode: host
        build: 
          context: .
          dockerfile: dockerfile
        env_file:
          - hammerdb.env
        environment:
          - RUN_MODE
          - BENCHMARK
        volumes:
          - ./scripts:/opt/HammerDB-4.7/scripts
          - ./output:/tmp
        command: ["/entrypoint.sh"]